language: php

node_js:
- "0.10"

sudo: false

php:
- 7
- 5.2

env:
- WP_VERSION=latest

install:
- npm install grunt-cli
- npm install
  
before_script:
- node_modules/grunt-cli/bin/grunt test_build
- bash bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION

script: 
- PHPRC=. WP_TESTS_DIR=/tmp/wordpress-tests-lib phpunit
