language: php

node_js:
- "0.10"

php:
- 7

env:
- WP_VERSION=latest

before_install:
- sudo apt-get -qq update
- sudo apt-get install php-intl

install:
- npm install grunt-cli
- npm install
  
before_script:
- node_modules/grunt-cli/bin/grunt test_build
- bash bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION

script: 
- PHPRC=. WP_TESTS_DIR=/tmp/wordpress-tests-lib phpunit
